require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, '10.0'

target 'jigsaw' do
  config = use_native_modules!

  use_react_native!(:path => config["reactNativePath"])

  pod 'react-native-image-editor', :path => '../node_modules/@react-native-community/image-editor'

  pod 'RNCMaskedView', :path => '../node_modules/@react-native-community/masked-view'

  pod 'react-native-view-shot', :path => '../node_modules/react-native-view-shot'

  pod 'RNImageTools', :path => '../node_modules/react-native-image-tools-wm'

  target 'jigsawTests' do
    inherit! :complete
    # Pods for testing
  end

  # Enables Flipper.
  #
  # Note that if you have use_frameworks! enabled, Flipper will not work and
  # you should disable these next few lines.
  use_flipper!
  post_install do |installer|
    flipper_post_install(installer)
  end
end

target 'jigsaw-tvOS' do
  # Pods for jigsaw-tvOS

  target 'jigsaw-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end
end
